version: "3"
services:
  laravel:
    container_name: Kalypso_LARAVEL
    tty: true
    image: bitnami/laravel:7
    depends_on:
      - mysql
      - redis
      - go
    ports:
      - "8001:8001"
    networks:
       - Kalypso_network
    volumes:
      - ./backend/laravel:/app
    command: >
      bash -c " composer install
      && php artisan route:list
      && php artisan key:generate
      && php artisan migrate
      && php artisan migrate:refresh
      && php artisan db:seed
      && php artisan serve --host=0.0.0.0 --port=8001"
  go:
    build: ./backend/go
    container_name: Kalypso_GO
    working_dir: /home/usuario/Documentos/2nDaw/Servidor/Projects_go/src/github.com/canaz/Kalypso_Go-gin-gonic_Laravel_Angular/backend/go
    volumes:
      - ./backend/go:/home/usuario/Documentos/2nDaw/Servidor/Projects_go/src/github.com/canaz/Kalypso_Go-gin-gonic_Laravel_Angular/backend/go
    ports:
      - "3000:3000"
    networks:
       - Kalypso_network
    depends_on:
      - mysql
      - redis
    labels:
      traefik.backend: "go"
      traefik.frontend.rule: "PathPrefix:/"
    environment:
      - GOROOT=/usr/local/go
      - GOPATH=/home/usuario/Documentos/2nDaw/Servidor/Projects_go/
      - "REDIS_URL= redis:6380"
    command: fresh
  mysql:
    container_name: Kalypso_MYSQL
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: on-failure
    networks:
       - Kalypso_network
    volumes:
      - mysqlBackup:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kalypso
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  
  redis:
    container_name: Kalypso_REDIS
    image: redis:alpine
    restart: on-failure
    ports:
      - "6380:6380"
    volumes:
      - "redis:/redis_data"
  traefik:
    image:  traefik:1.7.2-alpine
    container_name: traefik_container
    ports:
      - "80:80"
      - "8080:8080"
    networks:
       - Kalypso_network
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock 
       - ./common/traefik:/etc/traefik
volumes:
  redis:
  mysqlBackup:
networks:
   Kalypso_network: {}
