version: '3'
services:
  laravel:
    build: ./backend/laravel
    ports:
    - "8000:8000"
    networks:
    - kalypso_network
    depends_on:
    - mysql
  go:
    build: ./backend/go
    ports:
     - "3000:3000"
    networks:
     - kalypso_network
    depends_on:
     - mysql
  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    networks:
    - kalypso_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Kalypso
      MYSQL_USER: root
      MYSQL_PASSWORD: 
networks:
    kalypso_network: