version: "3"
services:
  laravel:
    tty: true
    image: bitnami/laravel:7
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8003:3001
    volumes:
      - ./backend/laravel:/app
    command: >
      bash -c "php artisan route:list
      && php artisan key:generate
      && php artisan migrate
      && php artisan db:seed
      && php artisan serve --host=0.0.0.0 --port=3000"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - mysqlBackup:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kalypso
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  go:
    image: golang:1.15.2-alpine
    container_name: Kalypso_go
    working_dir: $HOME/Documentos/2nDaw/Servidor/Projects_go/src/github.com/canaz/Kalypso_Go-gin-gonic_Laravel_Angular
    volumes:
    - ./backend/go:$HOME/Documentos/2nDaw/Servidor/Projects_go/src/github.com/canaz/Kalypso_Go-gin-gonic_Laravel_Angular/backend/go/
    ports:
    - "3000:3000"
    restart: on-failure
    links:
    - mysql
    depends_on:
    - mysql
    environment:
    - GOROOT=/usr/local/go
    - GOPATH=/home/usuario/Documentos/2nDaw/Servidor/Projects_go/
    command: bash -c "govendor sync && fresh"
  angular:
    build: ./frontend
    working_dir: /app
    volumes:
    - ./frontend:/app
    ports:
    - "4200:4200"
    restart: on-failure
    links:
    - laravel
    depends_on:
    - laravel
    command: bash -c "npm install && ng serve --host=0.0.0.0 --port=4200"
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - "6380:6379"
    volumes:
      - "redis:/redis_data"
volumes:
  redis:
  mysqlBackup:
