global:
  scrape_interval: 5s
  evaluation_interval: 30s
scrape_configs:
  - job_name: "Kalypso-app"
    honor_labels: true
    static_configs:
      - targets: ["myapp_practica:3000"] 

    
  - job_name : "Traefik"
    honor_labels: true
    static_configs:
      - targets: ["Kalypso_LARAVEL:8001"]